### ISSUE TITLE
Can't we just even?

### ISSUE THREAD

**Issue by laughingclouds** [samuelmarina/is-odd#19]
The [is-even](https://github.com/samuelmarina/is-even) project is amazing, and I was thinking if we could use that package as a dependency to _this_ project (I think you can imagine where this is going).

We can use the isEven function to check if the number is even, if it returns false, it's odd. That way everyone can focus all their manpower on just the is-even project.

Please do correct me if I'm wrong.

**Comment by moonthug** [comment]
Sounds like quite a lot of additional dependencies

**Comment by laughingclouds** [comment]
> Sounds like quite a lot of additional dependencies

Well, I won't deny that. But it also reduces the job of maintaining **two** very important repositories to maintaining **just one** very important repository. 

Also, since numbers can stretch to infinity, it would be better if we try to cover just one infinity (I know this doesn't reduce the complexity and size of the projects because well, infinity taken with some other infinity is just another infinity). 

(But still, in my opinion "one infinity" sounds much better than "two infinities")

**Comment by starikcetin** [comment]
Nah, negation has too much overhead.

**Comment by laughingclouds** [comment]
> Nah, negation has too much overhead.

Should I close this issue then? Or wait for any contributor to close it?

**Comment by starikcetin** [comment]
> > Nah, negation has too much overhead.
> 
> Should I close this issue then? Or wait for any contributor to close it?

You can even things out by waiting for a contributor, but that would be a little odd.

**Comment by laughingclouds** [comment]
> > > Nah, negation has too much overhead.
> > 
> > 
> > Should I close this issue then? Or wait for any contributor to close it?
> 
> You can even things out by waiting for a contributor, but that would be a little odd.

Since an odd outcome is what I'm looking for, I'll wait.

**Comment by laughingclouds** [comment]
> > > > Nah, negation has too much overhead.
> > > 
> > > 
> > > Should I close this issue then? Or wait for any contributor to close it?
> > 
> > 
> > You can even things out by waiting for a contributor, but that would be a little odd.
> 
> Since an odd outcome is what I'm looking for, I'll wait.

Ok so, since I will be waiting, I believe an indefinite (as indefinite as the future size of this project) wait would be the best wait for my odd outcome. 

After multiple deliberation with my soul, this was the only reply I could get. Hence, I @laughingclouds the author of issue [#19](https://github.com/samuelmarina/is-odd/issues/19) and pull request #20 am now voluntarily closing this issue.

Bye lol.

**Comment by starikcetin** [comment]
Even issues don't get responses, such an odd repo.
